spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST_LOCAL:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bookingdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

  data:
    redis:
      host: ${REDIS_HOST_LOCAL:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_HOST_LOCAL:localhost}:${KAFKA_PORT_LOCAL:9092}