spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST_DEV:booking-db}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bookingdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOST_DEV:booking-redis}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_HOST_DEV:kafka}:${KAFKA_PORT_DEV:29092}